### ISSUE TITLE
Load mqttws31.js from CDN

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-aws-iot#10]
http://git.eclipse.org/c/paho/org.eclipse.paho.mqtt.javascript.git/plain/src/mqttws31.js

**Comment by pherris** [comment]
should be resolved by https://github.com/dwyl/learn-aws-iot/pull/22

**Comment by nelsonic** [comment]
@pherris thanks for updating that! ❤️  ✅  🎉
