### ISSUE TITLE
websocket demo screenshots

### ISSUE THREAD

**Issue by jackcarlisle** [dwyl/learn-aws-iot#13]

**Comment by jackcarlisle** [comment]
<img width="1677" alt="screen shot 2016-02-17 at 16 50 57" src="https://cloud.githubusercontent.com/assets/12450298/13117207/de1230ae-d596-11e5-9192-0a0d4f225826.png">

**Comment by jackcarlisle** [comment]
![screen shot 2016-02-17 at 16 50 57](https://cloud.githubusercontent.com/assets/12450298/13117245/f7fdb704-d596-11e5-8e6c-9b7309623038.png)

**Comment by jackcarlisle** [comment]
<img width="1668" alt="screen shot 2016-02-17 at 16 55 08" src="https://cloud.githubusercontent.com/assets/12450298/13117299/39d000b0-d597-11e5-83ac-cb9639315343.png">

**Comment by jackcarlisle** [comment]
![screen shot 2016-02-17 at 16 59 32](https://cloud.githubusercontent.com/assets/12450298/13117471/fe24f254-d597-11e5-8839-8ac7fd387fbe.png)

**Comment by jackcarlisle** [comment]
<img width="1663" alt="screen shot 2016-02-17 at 16 59 43" src="https://cloud.githubusercontent.com/assets/12450298/13117555/5d74fa6a-d598-11e5-8b5a-9c5aa39f1cc1.png">

**Comment by jackcarlisle** [comment]
<img width="1673" alt="screen shot 2016-02-17 at 16 59 59" src="https://cloud.githubusercontent.com/assets/12450298/13117592/805dc412-d598-11e5-8dbf-c7349941f88c.png">

**Comment by jackcarlisle** [comment]
<img width="1678" alt="screen shot 2016-02-17 at 17 05 27" src="https://cloud.githubusercontent.com/assets/12450298/13117634/b41925f8-d598-11e5-9a4c-57a94ba45ee6.png">

**Comment by jackcarlisle** [comment]
<img width="1673" alt="screen shot 2016-02-17 at 17 05 45" src="https://cloud.githubusercontent.com/assets/12450298/13117693/ef600dfc-d598-11e5-8d19-0f2345915f26.png">

**Comment by jackcarlisle** [comment]
![screen shot 2016-02-17 at 17 26 36](https://cloud.githubusercontent.com/assets/12450298/13118451/18333d00-d59c-11e5-9fb0-f75507c6094c.png)

**Comment by jackcarlisle** [comment]
![screen shot 2016-02-17 at 17 26 58 2](https://cloud.githubusercontent.com/assets/12450298/13118468/3463042e-d59c-11e5-96e3-c26b4676d084.png)

**Comment by jackcarlisle** [comment]
![screen shot 2016-02-17 at 17 26 59](https://cloud.githubusercontent.com/assets/12450298/13118502/59639694-d59c-11e5-8b20-2bfaf1a17f7f.png)

**Comment by jackcarlisle** [comment]
![screen shot 2016-02-17 at 17 27 33](https://cloud.githubusercontent.com/assets/12450298/13118527/76a46a58-d59c-11e5-932b-7e2fa69ebef3.png)

**Comment by jackcarlisle** [comment]
![screen shot 2016-02-17 at 17 27 41](https://cloud.githubusercontent.com/assets/12450298/13118538/89e06e78-d59c-11e5-9e8a-f83e4b4f0ccf.png)

**Comment by jackcarlisle** [comment]
![screen shot 2016-02-17 at 16 59 59](https://cloud.githubusercontent.com/assets/12450298/13118675/3e7b3b92-d59d-11e5-9238-d96d5d71f75c.png)

**Comment by nelsonic** [comment]
These Screenshots have all been included in #12 :white_check_mark:
