### ISSUE TITLE
Webpack Build Fails

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-aws-iot#16]
Hi Jack,
I just tried to run this locally, `npm install && npm run dev:start` and got:
![learn-iot-webpack-fail](https://cloud.githubusercontent.com/assets/194400/14858842/8696e40c-0c99-11e6-920f-57452e3e44c5.png)
Do we _need_ React/WebPack for this demo...?

**Comment by jackcarlisle** [comment]
@nelsonic React/WebPack not needed, a simpler example would be better! Links to #19

**Comment by nelsonic** [comment]
agree 100% thanks! closing.
