### ISSUE TITLE
how to get congnito identity id in lambda function?

### ISSUE THREAD

**Issue by jadhavmanoj** [dwyl/learn-aws-iot#24]
I have configured topic and rule to invoke lambda function. function invoked properly.
but I am not able to get identity id in context.identity object. 

whereas aws doc says, 
`the Lambda functions use resource-based policy, where the policy is the
Lambda functions use resource-based policy, where the policy is 
attached directly to the Lambda function itself. When creating a 
rule that invokes a Lambda function, you do not pass a role, so the 
user creating the rule does not need the iam:PassRole permission.`

ref ink:  https://docs.aws.amazon.com/iot/latest/developerguide/pass-role.html

need help.

**Comment by nelsonic** [comment]
This is a question to ask people @AWS directly. 
e.g: https://forums.aws.amazon.com/thread.jspa?threadID=223889
